version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=ecom
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ecom
    ports:
      - 5431:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6378:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8099:8000
    environment:
      - DB_HOST=db
      - DB_USER=ecom
      - DB_PASS=12345
      - DB_PORT=5432
      - DB_NAME=ecom
      - DEBUG=True
      - SECRET_KEY=m7ai5_&crfg7+u8x^ocvd1ha=mf_jwo)+%!iwk#_(dfl_n6#&!
