# Generated by Django 2.2.7 on 2020-02-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('DEVICE', 'device'), ('GARMENTS', 'garments'), ('ACCESSORIES', 'accessories')], default='DEVICE', max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
    ]
